title: Cumulus Design
icon: mdi:waves

views:
  - title: Cumulus Design
    path: cumulus-design
    icon: mdi:waves
    cards:
      - type: entities
        title: Test Cumulus Design
        entities:
          - sun.sun
