# ╔══════════════════════════════════════════════════════════════════════════╗
# ║ CUMULUS INTELLIGENT - AUTOMATIONS MODE PV                                  ║
# ║ Gestion intelligente du chauffage solaire                                  ║
# ╚══════════════════════════════════════════════════════════════════════════╝

automation:
  # ┌─────────────────────────────────────────────────────────────────────────┐
  # │ DÉMARRAGE PV INTELLIGENT                                                │
  # └─────────────────────────────────────────────────────────────────────────┘
  - id: cumulus_demarrage_pv_intelligent
    alias: "Cumulus - Démarrage PV intelligent"
    description: "Démarre le cumulus quand conditions PV optimales"
    mode: restart  # Redémarre si retriggered pendant le délai

    trigger:
      # Trigger principal : puissance APS suffisante
      - platform: numeric_state
        entity_id: sensor.cumulus_production_aps_w
        above: input_number.cumulus_seuil_pv_statique_w
        for:
          seconds: input_number.cumulus_delai_on_secondes
        id: trigger_puissance

      # Trigger alternatif : changement conditions
      - platform: state
        entity_id: binary_sensor.cumulus_conditions_pv_ok
        to: 'on'
        for:
          seconds: 30
        id: trigger_conditions

      # Trigger boost : batterie pleine
      - platform: numeric_state
        entity_id: sensor.cumulus_soc_batterie
        above: 95
        for:
          minutes: 5
        id: trigger_soc_full

    condition:
      # Toutes les conditions doivent être remplies
      - condition: and
        conditions:
          # Cumulus pas déjà ON
          - condition: state
            entity_id: switch.shellypro1_ece334ee1b64
            state: 'off'

          # Dans la fenêtre PV
          - condition: state
            entity_id: binary_sensor.cumulus_fenetre_pv
            state: 'on'

          # Pas en mode vacances
          - condition: state
            entity_id: input_boolean.cumulus_mode_vacances
            state: 'off'

          # Pas de verrou deadband
          - condition: state
            entity_id: input_boolean.cumulus_verrou_deadband
            state: 'off'

          # Conditions spécifiques selon trigger
          - condition: or
            conditions:
              # Si trigger puissance : vérifier aussi SOC
              - condition: and
                conditions:
                  - condition: trigger
                    id: trigger_puissance
                  - condition: numeric_state
                    entity_id: sensor.cumulus_soc_batterie
                    above: input_number.cumulus_soc_min

              # Si trigger conditions : tout est déjà vérifié
              - condition: trigger
                id: trigger_conditions

              # Si trigger SOC full : vérifier puissance minimale
              - condition: and
                conditions:
                  - condition: trigger
                    id: trigger_soc_full
                  - condition: numeric_state
                    entity_id: sensor.cumulus_production_aps_w
                    above: 50  # Minimum 50W si batterie pleine

    action:
      # Log du démarrage avec contexte
      - service: logbook.log
        data:
          name: "Cumulus PV"
          message: >
            Démarrage PV -
            Trigger: {{ trigger.id }} |
            APS: {{ states('sensor.cumulus_production_aps_w') }}W |
            SOC: {{ states('sensor.cumulus_soc_batterie') }}% |
            Seuil: {{ states('input_number.cumulus_seuil_pv_statique_w') }}W
          entity_id: switch.shellypro1_ece334ee1b64
          domain: automation

      # Notification si activées
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.cumulus_notifications_actives
                state: 'on'
            sequence:
              - service: notify.notify
                data:
                  title: "☀️ Cumulus - Démarrage solaire"
                  message: >
                    Le cumulus démarre en mode solaire.
                    Production: {{ states('sensor.cumulus_pv_power_w') }}W
                    Batterie: {{ states('sensor.cumulus_soc_batterie') }}%

      # Enregistrer la raison du démarrage
      - service: input_text.set_value
        target:
          entity_id: input_text.cumulus_raison_arret
        data:
          value: "Démarrage PV à {{ now().strftime('%H:%M') }}"

      # DÉMARRER LE CUMULUS
      - service: switch.turn_on
        target:
          entity_id: switch.shellypro1_ece334ee1b64

      # Attendre confirmation
      - wait_template: "{{ is_state('switch.shellypro1_ece334ee1b64', 'on') }}"
        timeout: '00:00:10'
        continue_on_timeout: false

      # Démarrer le timer de chauffe
      - service: timer.start
        target:
          entity_id: timer.cumulus_timer_chauffe
        data:
          duration: '02:30:00'

      # Incrémenter compteur
      - service: counter.increment
        target:
          entity_id: counter.cumulus_chauffes_jour

  # ┌─────────────────────────────────────────────────────────────────────────┐
  # │ ARRÊT PV INTELLIGENT                                                    │
  # └─────────────────────────────────────────────────────────────────────────┘
  - id: cumulus_arret_pv_intelligent
    alias: "Cumulus - Arrêt PV intelligent"
    description: "Arrête le cumulus si conditions PV insuffisantes"
    mode: single

    trigger:
      # Production insuffisante
      - platform: numeric_state
        entity_id: sensor.cumulus_production_aps_w
        below: input_number.cumulus_seuil_pv_statique_w
        for:
          seconds: input_number.cumulus_delai_off_secondes
        id: trigger_production_basse

      # SOC trop bas
      - platform: numeric_state
        entity_id: sensor.cumulus_soc_batterie
        below: input_number.cumulus_soc_min
        for:
          seconds: 30
        id: trigger_soc_bas

      # Fin fenêtre PV
      - platform: state
        entity_id: binary_sensor.cumulus_fenetre_pv
        to: 'off'
        id: trigger_fin_fenetre

      # Température atteinte
      - platform: numeric_state
        entity_id: sensor.cumulus_temperature_estimee
        above: input_number.cumulus_temperature_cible_pv
        for:
          minutes: 5
        id: trigger_temperature_ok

    condition:
      # Cumulus doit être ON et en mode PV
      - condition: state
        entity_id: switch.shellypro1_ece334ee1b64
        state: 'on'
      - condition: state
        entity_id: sensor.cumulus_mode_actif
        state: 'PV'

    action:
      # Déterminer la raison de l'arrêt
      - service: input_text.set_value
        target:
          entity_id: input_text.cumulus_raison_arret
        data:
          value: >
            {% if trigger.id == 'trigger_production_basse' %}
              Production insuffisante ({{ states('sensor.cumulus_production_aps_w') }}W)
            {% elif trigger.id == 'trigger_soc_bas' %}
              SOC batterie trop bas ({{ states('sensor.cumulus_soc_batterie') }}%)
            {% elif trigger.id == 'trigger_fin_fenetre' %}
              Fin de la fenêtre PV
            {% elif trigger.id == 'trigger_temperature_ok' %}
              Température cible atteinte ({{ states('sensor.cumulus_temperature_estimee') }}°C)
            {% else %}
              Arrêt PV - raison inconnue
            {% endif %}

      # Log
      - service: logbook.log
        data:
          name: "Cumulus PV"
          message: "Arrêt - {{ states('input_text.cumulus_raison_arret') }}"
          entity_id: switch.shellypro1_ece334ee1b64

      # Activer deadband si nécessaire
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.id in ['trigger_production_basse', 'trigger_soc_bas'] }}"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.cumulus_verrou_deadband
              - service: input_text.set_value
                target:
                  entity_id: input_text.cumulus_raison_deadband
                data:
                  value: "{{ states('input_text.cumulus_raison_arret') }}"
              - service: timer.start
                target:
                  entity_id: timer.cumulus_timer_deadband

      # ARRÊTER LE CUMULUS
      - service: switch.turn_off
        target:
          entity_id: switch.shellypro1_ece334ee1b64

      # Arrêter le timer
      - service: timer.cancel
        target:
          entity_id: timer.cumulus_timer_chauffe

  # ┌─────────────────────────────────────────────────────────────────────────┐
  # │ LIMITEUR IMPORT RÉSEAU                                                  │
  # └─────────────────────────────────────────────────────────────────────────┘
  - id: cumulus_limiteur_import_reseau
    alias: "Cumulus - Limiteur import réseau"
    description: "Arrête le cumulus si import réseau excessif"
    mode: single

    trigger:
      - platform: numeric_state
        entity_id: sensor.cumulus_import_reseau_w
        above: input_number.cumulus_import_max_w
        for:
          seconds: 5  # Réaction rapide pour limiter import

    condition:
      - condition: state
        entity_id: switch.shellypro1_ece334ee1b64
        state: 'on'
      - condition: state
        entity_id: sensor.cumulus_mode_actif
        state: 'PV'

    action:
      # Log urgence
      - service: logbook.log
        data:
          name: "Cumulus Limiteur"
          message: >
            URGENCE - Import excessif: {{ states('sensor.cumulus_import_reseau_w') }}W
            (max: {{ states('input_number.cumulus_import_max_w') }}W)
          entity_id: switch.shellypro1_ece334ee1b64
          domain: automation

      # Arrêt immédiat
      - service: switch.turn_off
        target:
          entity_id: switch.shellypro1_ece334ee1b64

      # Deadband prolongé
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.cumulus_verrou_deadband
      - service: input_text.set_value
        target:
          entity_id: input_text.cumulus_raison_deadband
        data:
          value: "Import réseau excessif"
      - service: timer.start
        target:
          entity_id: timer.cumulus_timer_deadband
        data:
          duration: '00:10:00'  # 10 minutes de deadband

  # ┌─────────────────────────────────────────────────────────────────────────┐
  # │ OPTIMISATION APPAREILS PRIORITAIRES                                     │
  # └─────────────────────────────────────────────────────────────────────────┘
  - id: cumulus_gestion_appareils_prioritaires
    alias: "Cumulus - Gestion appareils prioritaires"
    description: "Suspend le cumulus si appareils prioritaires actifs"
    mode: restart

    trigger:
      # Lave-linge démarre
      - platform: numeric_state
        entity_id: sensor.lave_linge_power
        above: 100
        id: lave_linge_on

      # Lave-vaisselle démarre
      - platform: numeric_state
        entity_id: sensor.lave_vaisselle_power
        above: 100
        id: lave_vaisselle_on

      # Appareils s'arrêtent
      - platform: numeric_state
        entity_id: sensor.lave_linge_power
        below: 10
        for:
          minutes: 2
        id: lave_linge_off

      - platform: numeric_state
        entity_id: sensor.lave_vaisselle_power
        below: 10
        for:
          minutes: 2
        id: lave_vaisselle_off

    condition:
      - condition: state
        entity_id: binary_sensor.cumulus_fenetre_pv
        state: 'on'

    action:
      - choose:
          # Si appareil prioritaire démarre et cumulus ON
          - conditions:
              - condition: template
                value_template: "{{ trigger.id in ['lave_linge_on', 'lave_vaisselle_on'] }}"
              - condition: state
                entity_id: switch.shellypro1_ece334ee1b64
                state: 'on'
              - condition: state
                entity_id: sensor.cumulus_mode_actif
                state: 'PV'
            sequence:
              # Vérifier si puissance insuffisante
              - condition: template
                value_template: >
                  {% set pv_total = states('sensor.cumulus_pv_power_w') | float(0) %}
                  {% set appareil = 2000 if 'linge' in trigger.id else 2500 %}
                  {{ pv_total < (3000 + appareil - 500) }}  # 500W de marge

              # Suspendre cumulus
              - service: logbook.log
                data:
                  name: "Cumulus Priorité"
                  message: >
                    Suspension pour {{ 'lave-linge' if 'linge' in trigger.id else 'lave-vaisselle' }}
              - service: switch.turn_off
                target:
                  entity_id: switch.shellypro1_ece334ee1b64
              - service: input_text.set_value
                target:
                  entity_id: input_text.cumulus_raison_arret
                data:
                  value: "Priorité {{ 'lave-linge' if 'linge' in trigger.id else 'lave-vaisselle' }}"

          # Si appareils s'arrêtent et conditions OK
          - conditions:
              - condition: template
                value_template: "{{ trigger.id in ['lave_linge_off', 'lave_vaisselle_off'] }}"
              - condition: state
                entity_id: switch.shellypro1_ece334ee1b64
                state: 'off'
              - condition: state
                entity_id: binary_sensor.cumulus_conditions_pv_ok
                state: 'on'
            sequence:
              # Vérifier qu'aucun autre appareil n'est actif
              - condition: template
                value_template: >
                  {% set linge = states('sensor.lave_linge_power') | float(0) %}
                  {% set vaisselle = states('sensor.lave_vaisselle_power') | float(0) %}
                  {{ linge < 10 and vaisselle < 10 }}

              # Redémarrer cumulus
              - service: logbook.log
                data:
                  name: "Cumulus Priorité"
                  message: "Reprise après arrêt appareils prioritaires"
              - service: switch.turn_on
                target:
                  entity_id: switch.shellypro1_ece334ee1b64

  # ┌─────────────────────────────────────────────────────────────────────────┐
  # │ RESET DEADBAND                                                          │
  # └─────────────────────────────────────────────────────────────────────────┘
  - id: cumulus_reset_deadband
    alias: "Cumulus - Reset deadband"
    description: "Réinitialise le verrou deadband après temporisation"
    mode: single

    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.cumulus_timer_deadband

    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.cumulus_verrou_deadband

      - service: input_text.set_value
        target:
          entity_id: input_text.cumulus_raison_deadband
        data:
          value: "Aucun"

      - service: logbook.log
        data:
          name: "Cumulus Deadband"
          message: "Verrou deadband réinitialisé"
