###############################################################################
# SDB_DOUCHE - v2025-09-30a-nomode-retry
# Douche SDB (Isa) - GARANTI sans changement de hvac_mode
# - Boost 22 degC a -2h30 du 1er cours ; eco 18.5 degC a -0h30.
# - Compatible Versatile Thermostat : attend la sonde, pose la consigne, verifie,
#   reessaie (script + automatismes), notifie en cas d'echec.
# - Ajoute un suivi de consigne demandee + 2 capteurs d'etat.
###############################################################################

input_text:
  sdb_entity_climate:
    name: ENTITE - Thermostat salle de bain (climate.*)
    icon: mdi:thermometer
    initial: climate.thermostat_sdb

  sdb_temp_sensor:
    name: ENTITE - Sonde T SDB (sensor.*)
    icon: mdi:thermometer
    initial: sensor.thermo_sdb_temperature

  sdb_last_preset:
    name: SDB - Dernier preset demande
    icon: mdi:thermometer-lines
    initial: ""

input_number:
  sdb_temp_confort_c:
    name: SDB - Consigne Confort (degC)
    unit_of_measurement: "degC"
    min: 15
    max: 30
    step: 0.5
    icon: mdi:home-thermometer
    initial: 22.0
  sdb_temp_eco_c:
    name: SDB - Consigne Eco (degC)
    unit_of_measurement: "degC"
    min: 12
    max: 25
    step: 0.5
    icon: mdi:leaf
    initial: 18.5
  sdb_last_setpoint_c:
    name: SDB - Derniere consigne demandee (degC)
    unit_of_measurement: "degC"
    min: 0
    max: 40
    step: 0.1
    icon: mdi:thermometer-alert
    initial: 0

input_boolean:
  sdb_reveil_enable:
    name: SDB - Reveil douche actif
    icon: mdi:toggle-switch
    initial: true

script:
  sdb_set_temp:
    alias: SDB - Appliquer consigne (no-mode-change + wait-temp)
    mode: parallel
    max: 10
    fields:
      climate_entity:
        description: "Entite climate.* de la salle de bain"
        example: "climate.salle_de_bain"
      temp:
        description: "Consigne en degC"
        example: 22.0
    sequence:
      - variables:
          ce: "{{ (climate_entity | default(states('input_text.sdb_entity_climate'))) | string | trim }}"
          t: "{{ temp | float(default=22) }}"
          exists: "{{ states(ce) not in ['unknown','unavailable',''] }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ exists }}"
            sequence:
              - service: input_number.set_value
                data:
                  entity_id: input_number.sdb_last_setpoint_c
                  value: "{{ t }}"
              - service: climate.turn_on
                data:
                  entity_id: "{{ ce }}"
              - wait_template: >-
                  {{ state_attr(ce, 'current_temperature') is number }}
                timeout: "00:00:30"
                continue_on_timeout: true
              - service: climate.set_temperature
                data:
                  entity_id: "{{ ce }}"
                  temperature: "{{ t }}"
              - variables:
                  ok_now: >-
                    {% set cur = state_attr(ce, 'temperature') %}
                    {{ cur is number and (cur - t) | abs < 0.2 }}
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ not ok_now }}"
                    sequence:
                      - delay: "00:00:03"
                      - service: climate.set_temperature
                        data:
                          entity_id: "{{ ce }}"
                          temperature: "{{ t }}"
                      - wait_template: >-
                          {% set cur = state_attr(ce, 'temperature') %}
                          {{ cur is number and (cur - t) | abs < 0.2 }}
                        timeout: "00:00:10"
                        continue_on_timeout: true
                      - variables:
                          ok_final: >-
                            {% set cur = state_attr(ce, 'temperature') %}
                            {{ cur is number and (cur - t) | abs < 0.2 }}
                      - choose:
                          - conditions:
                              - condition: template
                                value_template: "{{ not ok_final }}"
                            sequence:
                              - service: persistent_notification.create
                                data:
                                  title: "SDB - Consigne non confirmee"
                                  message: >-
                                    Impossible de confirmer la consigne {{ t }} degC pour {{ ce }}.
                                    (Mode HVAC non modifie.) Verifiez preset/mode actuel et l'entite
                                    dans input_text.sdb_entity_climate.
                                  notification_id: sdb_setpoint_error
          - conditions: []
            sequence:
              - service: persistent_notification.create
                data:
                  title: "SDB - Entite climate introuvable"
                  message: >-
                    L'entite '{{ ce }}' n'existe pas ou est indisponible.
                    Mettez a jour input_text.sdb_entity_climate.
                  notification_id: sdb_missing_climate

  sdb_set_preset:
    alias: SDB - Changer mode preset (confort/eco)
    mode: parallel
    max: 10
    fields:
      climate_entity:
        description: "Entite climate.* de la salle de bain"
        example: "climate.salle_de_bain"
      preset:
        description: "Mode preset (comfort ou eco)"
        example: "comfort"
    sequence:
      - variables:
          ce: "{{ (climate_entity | default(states('input_text.sdb_entity_climate'))) | string | trim }}"
          p: "{{ preset | string | lower }}"
          exists: "{{ states(ce) not in ['unknown','unavailable',''] }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ exists }}"
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.sdb_last_preset
                  value: "{{ p }}"
              - service: climate.turn_on
                data:
                  entity_id: "{{ ce }}"
              - wait_template: >-
                  {{ state_attr(ce, 'current_temperature') is number }}
                timeout: "00:00:30"
                continue_on_timeout: true
              - service: climate.set_preset_mode
                data:
                  entity_id: "{{ ce }}"
                  preset_mode: "{{ p }}"
              - delay: "00:00:02"
              - variables:
                  ok_now: >-
                    {% set cur = state_attr(ce, 'preset_mode') %}
                    {{ cur is not none and cur | lower == p }}
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ not ok_now }}"
                    sequence:
                      - delay: "00:00:03"
                      - service: climate.set_preset_mode
                        data:
                          entity_id: "{{ ce }}"
                          preset_mode: "{{ p }}"
                      - wait_template: >-
                          {% set cur = state_attr(ce, 'preset_mode') %}
                          {{ cur is not none and cur | lower == p }}
                        timeout: "00:00:10"
                        continue_on_timeout: true
                      - variables:
                          ok_final: >-
                            {% set cur = state_attr(ce, 'preset_mode') %}
                            {{ cur is not none and cur | lower == p }}
                      - choose:
                          - conditions:
                              - condition: template
                                value_template: "{{ not ok_final }}"
                            sequence:
                              - service: persistent_notification.create
                                data:
                                  title: "SDB - Preset non confirme"
                                  message: >-
                                    Impossible de confirmer le preset {{ p }} pour {{ ce }}.
                                    Verifiez les presets disponibles et l'entite
                                    dans input_text.sdb_entity_climate.
                                  notification_id: sdb_preset_error
          - conditions: []
            sequence:
              - service: persistent_notification.create
                data:
                  title: "SDB - Entite climate introuvable"
                  message: >-
                    L'entite '{{ ce }}' n'existe pas ou est indisponible.
                    Mettez a jour input_text.sdb_entity_climate.
                  notification_id: sdb_missing_climate_preset

###############################################################################

template:
  - trigger:
      - platform: time_pattern
        seconds: "/15"
      - platform: state
        entity_id:
          - input_text.sdb_entity_climate
          - input_number.sdb_last_setpoint_c
          - input_text.sdb_last_preset
    binary_sensor:
      - name: "SDB - Consigne confirmee"
        unique_id: sdb_consigne_confirmee
        state: >-
          {% set ce = states('input_text.sdb_entity_climate') | trim %}
          {% set req = states('input_number.sdb_last_setpoint_c') | float(0) %}
          {% set cur = state_attr(ce, 'temperature') %}
          {{ states(ce) not in ['unknown','unavailable',''] and req > 0 and cur is number and (cur - req) | abs < 0.2 }}
        icon: >-
          {% set s = this.state %}
          {{ 'mdi:check-circle' if s in ['on','true']
             else 'mdi:progress-clock' if s in ['unknown','unavailable'] else 'mdi:alert-circle' }}
        attributes:
          requested_setpoint: "{{ states('input_number.sdb_last_setpoint_c') }}"
          current_setpoint: >-
            {% set ce = states('input_text.sdb_entity_climate') | trim %}
            {{ state_attr(ce, 'temperature') }}
        availability: >-
          {% set ce = states('input_text.sdb_entity_climate') | trim %}
          {% set req = states('input_number.sdb_last_setpoint_c') %}
          {{ states(ce) not in ['unknown','unavailable',''] and req not in ['unknown','unavailable',''] }}

      - name: "SDB - Sonde temperature dispo"
        unique_id: sdb_sonde_temperature_dispo
        device_class: connectivity
        state: >-
          {% set ce = states('input_text.sdb_entity_climate') | trim %}
          {{ state_attr(ce, 'current_temperature') is number }}
        icon: >-
          {% set s = this.state %}
          {{ 'mdi:thermometer' if s in ['on','true'] else 'mdi:thermometer-off' if s == 'off' else 'mdi:help-circle' }}

      - name: "SDB - Preset confirme"
        unique_id: sdb_preset_confirme
        state: >-
          {% set ce = states('input_text.sdb_entity_climate') | trim %}
          {% set req = states('input_text.sdb_last_preset') | lower %}
          {% set cur = state_attr(ce, 'preset_mode') %}
          {{ states(ce) not in ['unknown','unavailable',''] and req != '' and cur is not none and cur | lower == req }}
        icon: >-
          {% set s = this.state %}
          {{ 'mdi:check-circle' if s in ['on','true']
             else 'mdi:progress-clock' if s in ['unknown','unavailable'] else 'mdi:alert-circle' }}
        attributes:
          requested_preset: "{{ states('input_text.sdb_last_preset') }}"
          current_preset: >-
            {% set ce = states('input_text.sdb_entity_climate') | trim %}
            {{ state_attr(ce, 'preset_mode') }}
        availability: >-
          {% set ce = states('input_text.sdb_entity_climate') | trim %}
          {% set req = states('input_text.sdb_last_preset') %}
          {{ states(ce) not in ['unknown','unavailable',''] and req not in ['unknown','unavailable',''] }}

###############################################################################

automation:
  - id: '1709595278512'
    alias: "Reveil college chauffage douche"
    description: "Passe en mode confort 2h30 avant le 1er cours, puis repasse en mode eco deux heures apres."
    mode: single
    trigger:
      - platform: calendar
        entity_id: calendar.planning_cours_isa
        event: start
        offset: "-02:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.sdb_reveil_enable
        state: "on"
      - condition: state
        entity_id: calendar.vacances_scolaires
        state: "off"
      - condition: state
        entity_id: calendar.jours_feries_en_france
        state: "off"
      - condition: time
        before: "11:00:00"
      - condition: template
        value_template: >
          {% set last = this.attributes.last_triggered %}
          {{ last is none or (as_datetime(last)).date() != now().date() }}
    action:
      - variables:
          _ce: "{{ states('input_text.sdb_entity_climate') | trim }}"
          _max_retries_boost: 10
          _max_retries_eco: 6
      - repeat:
          sequence:
            - service: script.sdb_set_preset
              data:
                climate_entity: "{{ _ce }}"
                preset: "comfort"
            - delay: "00:00:30"
          until:
            - condition: template
              value_template: >
                {{ is_state('binary_sensor.sdb_preset_confirme','on') or repeat.index >= _max_retries_boost }}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ is_state('binary_sensor.sdb_preset_confirme','on') }}"
            sequence:
              - service: logbook.log
                data:
                  name: "SDB Boost"
                  message: "Mode confort confirme"
                  entity_id: "{{ _ce }}"
              - delay: "02:00:00"
              - repeat:
                  sequence:
                    - service: script.sdb_set_preset
                      data:
                        climate_entity: "{{ _ce }}"
                        preset: "eco"
                    - delay: "00:00:30"
                  until:
                    - condition: template
                      value_template: >
                        {{ is_state('binary_sensor.sdb_preset_confirme','on') or repeat.index >= _max_retries_eco }}
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state('binary_sensor.sdb_preset_confirme','on') }}"
                    sequence:
                      - service: logbook.log
                        data:
                          name: "SDB Eco"
                          message: "Mode eco confirme"
                          entity_id: "{{ _ce }}"
                default:
                  - service: logbook.log
                    data:
                      name: "SDB Eco"
                      message: "Mode eco NON confirme apres retries."
                      entity_id: "{{ _ce }}"
        default:
          - service: logbook.log
            data:
              name: "SDB Boost"
              message: "Mode confort NON confirme apres retries."
              entity_id: "{{ _ce }}"

  - id: '1732009800001'
    alias: "Douche matinale - Week-end/Vacances"
    description: "Passe en mode confort a 8h00 quand Isa ne va pas au college le matin (week-end, vacances, jours feries)"
    mode: single
    trigger:
      - platform: time
        at: "08:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.sdb_reveil_enable
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: calendar.vacances_scolaires
            state: "on"
          - condition: state
            entity_id: calendar.jours_feries_en_france
            state: "on"
          - condition: template
            value_template: >
              {% set ns = namespace(has_morning_course=false) %}
              {% set start_of_day = now().replace(hour=0, minute=0, second=0, microsecond=0) %}
              {% set cutoff_time = now().replace(hour=11, minute=0, second=0, microsecond=0) %}
              {% set course_start = state_attr('calendar.planning_cours_isa', 'start_time') %}
              {% if course_start is not none %}
                {% set course_dt = as_datetime(course_start) %}
                {% if course_dt is not none and start_of_day <= course_dt < cutoff_time %}
                  {% set ns.has_morning_course = true %}
                {% endif %}
              {% endif %}
              {{ not ns.has_morning_course }}
      - condition: template
        value_template: >
          {% set last = this.attributes.last_triggered %}
          {{ last is none or (as_datetime(last)).date() != now().date() }}
    action:
      - variables:
          _ce: "{{ states('input_text.sdb_entity_climate') | trim }}"
          _max_retries_boost: 10
          _max_retries_eco: 6
      - repeat:
          sequence:
            - service: script.sdb_set_preset
              data:
                climate_entity: "{{ _ce }}"
                preset: "comfort"
            - delay: "00:00:30"
          until:
            - condition: template
              value_template: >
                {{ is_state('binary_sensor.sdb_preset_confirme','on') or repeat.index >= _max_retries_boost }}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ is_state('binary_sensor.sdb_preset_confirme','on') }}"
            sequence:
              - service: logbook.log
                data:
                  name: "SDB Boost Week-end/Vacances"
                  message: "Mode confort confirme"
                  entity_id: "{{ _ce }}"
              - delay: "02:00:00"
              - repeat:
                  sequence:
                    - service: script.sdb_set_preset
                      data:
                        climate_entity: "{{ _ce }}"
                        preset: "eco"
                    - delay: "00:00:30"
                  until:
                    - condition: template
                      value_template: >
                        {{ is_state('binary_sensor.sdb_preset_confirme','on') or repeat.index >= _max_retries_eco }}
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state('binary_sensor.sdb_preset_confirme','on') }}"
                    sequence:
                      - service: logbook.log
                        data:
                          name: "SDB Eco Week-end/Vacances"
                          message: "Mode eco confirme"
                          entity_id: "{{ _ce }}"
                default:
                  - service: logbook.log
                    data:
                      name: "SDB Eco Week-end/Vacances"
                      message: "Mode eco NON confirme apres retries."
                      entity_id: "{{ _ce }}"
        default:
          - service: logbook.log
            data:
              name: "SDB Boost Week-end/Vacances"
              message: "Mode confort NON confirme apres retries."
              entity_id: "{{ _ce }}"
